{
 "title": "Liquidsoap",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "radio",
    "label": "Radio",
    "query": "label_values(liquidsoap_is_ready,radio)"
   },
   {
    "name": "type",
    "label": "Type",
    "query": "label_values(liquidsoap_is_ready,type)"
   },
   {
    "name": "name",
    "label": "Name",
    "query": "label_values(liquidsoap_is_ready,name)"
   }
  ]
 },
 "panels": [
  {
   "title": "$name Is Ready",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "repeat": "name",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "liquidsoap_is_ready{radio=~\"$radio\",type=~\"$type\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$name Is Ready",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "liquidsoap_is_ready{radio=~\"$radio\",type=~\"$type\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$name Is Ready",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "liquidsoap_is_ready{radio=~\"$radio\",type=~\"$type\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Now playing",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "liquidsoap_is_playing{radio=~\"$radio\"} > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Preferred livesource",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 3 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "liquidsoap_is_preferred_livesource{radio=~\"$radio\"} > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Is output blank",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "liquidsoap_is_blank{radio=~\"$radio\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Output source playing history",
   "type": "graph",
   "description": "0 = source is not playling\n1 = source is playling",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "liquidsoap_is_playing{radio=~\"$radio\"}",
     "legendFormat": "{{type}} {{name}}"
    }
   ]
  },
  {
   "title": "Input / Output Ready",
   "type": "graph",
   "description": "0 = source unready\n1 = source ready",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "liquidsoap_is_ready{radio=~\"$radio\",type=~\"$type\",name=~\"$name\"}",
     "legendFormat": "{{type}} {{name}}"
    }
   ]
  },
  {
   "title": "Input / Output Duration Unready per second",
   "type": "graph",
   "description": "0 = source unready\n1 = source ready",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(liquidsoap_duration_unready_seconds{radio=~\"$radio\",type=~\"$type\",name=~\"$name\"}[1m])",
     "legendFormat": "{{type}} {{name}}"
    }
   ]
  }
 ]
}